# Generated by Django 3.0.6 on 2020-06-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendapp.UserPro'),
        ),
        migrations.AlterField(
            model_name='emailfromlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendapp.UserPro'),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendapp.UserPro'),
        ),
    ]
